---
# Test Job: Technical Indicators with LOG_LEVEL workaround
apiVersion: batch/v1
kind: Job
metadata:
  name: test-indicators-simple
  namespace: financial-screener
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: technical-analyzer
        batch: test-simple
    spec:
      restartPolicy: Never
      containers:
      - name: technical-analyzer
        image: technical-analyzer:latest
        imagePullPolicy: Never
        command:
        - python
        - /app/src/main_indicators.py
        - --tickers
        - AAPL,MSFT,GOOGL
        - --force
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DATABASE_URL
        - name: DATABASE_SCHEMA
          value: "financial_screener"
        - name: LOG_LEVEL
          value: "DEBUG"  # This will trigger the error, so let's use Python's simple logging
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
