apiVersion: batch/v1
kind: Job
metadata:
  name: test-exchanges-parameter
  namespace: financial-screener
spec:
  ttlSecondsAfterFinished: 86400  # Keep for 24 hours
  template:
    metadata:
      labels:
        app: data-collector
        job-type: test
        batch: test-exchanges
    spec:
      restartPolicy: Never
      containers:
      - name: data-collector
        image: financial-data-collector:latest
        imagePullPolicy: Never
        command:
          - python
          - /app/src/main_enhanced.py
        args:
          - --execution-id
          - "test_exchanges_2025-10-27"
          - --exchanges
          - "TEST"
          - --mode
          - historical
          - --start-date
          - "2025-09-01"
          - --end-date
          - "2025-09-30"
          - --skip-existing
          - --batch-size
          - "3"
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: DATABASE_URL
          - name: EODHD_API_KEY
            valueFrom:
              secretKeyRef:
                name: data-api-secrets
                key: EODHD_API_KEY
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2000m"
            memory: "2Gi"
