---
apiVersion: v1
kind: Secret
metadata:
  name: data-api-secrets
  namespace: financial-screener
type: Opaque
stringData:
  # EODHD API - Primary data source
  # Paid All-In-One plan: 100,000 calls/day
  # Includes: EOD data, fundamentals, technical indicators, splits, dividends
  EODHD_API_KEY: "68f521d8d5e1f7.88465516"

  # Alpha Vantage API - Fallback source
  # Free tier: 25 calls/day
  ALPHAVANTAGE_API_KEY: "MIXOA8J4I3F5DIWN"
